
[font]
#normal = { family = "MesloLGSDZ Nerd Font Mono", style = "Regular" }
normal = { family = "JetBrainsMono", style = "Regular" }
size = 12

[window]
opacity = 0.7

[cursor]
style = { shape = "Block", blinking = "On" }
