set -g default-command "${SHELL}"
setw -g mouse on
set -g default-terminal "tmux-256color"

set -g prefix C-a
unbind C-b
bind C-a send-prefix

bind  c  new-window      -c "#{pane_current_path}"
bind  %  split-window -h -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"
