windowrulev2 = float,class:(qalculate-gtk)
windowrulev2 = float,class:(blueman-manager)
windowrulev2 = float,class:(pavucontrol)
windowrulev2 = float,class:(imv)
windowrulev2 = float,class:(wlogout)
windowrulev2 = workspace 2, class:(brave-browser)
windowrulev2 = workspace 3, class:(jetbrains-idea)
windowrulev2 = workspace 3, class:(code)
windowrulev2 = float, class:floating
windowrulev2 = idleinhibit[fullscreen], class:.*
