windowrule = float, ^(qalculate-gtk)$
windowrule = float,^(blueman-manager)$
windowrule = float,^(pavucontrol)$
windowrule = float,^(imv)$
windowrule = float,^(wlogout)$
# windowrulev2 = nomaximizerequest, class:.*
windowrulev2 = float, class:floating
windowrulev2 = idleinhibit[fullscreen], class:.*