workspace = 1, monitor:HDMI-A-1, monitor:desc:Acer Technologies SA270 0x12005313, default:true
workspace = 10, monitor:eDP-1, default:true

workspace = 1, on-created-empty:$terminal
workspace = 2, on-created-empty:$browser
workspace = special:terminal, on-created-empty:$terminal
workspace = special:spotify, on-created-empty:spotify
workspace = special:note-taking, on-created-empty:obsidian
workspace = special:vesktop, on-created-empty:vesktop
workspace = special:file-manager, on-created-empty:$fileManager
workspace = special:browser-incognito, on-created-empty:$browser -incognito
