monitor = HDMI-A-1,highrr,0x0,1
monitor = eDP-1,highrr,1920x0,1
# monitor = eDP-1,disable

# ---------- Mirror monitors -------------
# monitor = eDP-1,1920x1080@60,0x0,1
# monitor = ,1920x1080@60,auto,1,mirror,eDP-1