
# Wallpaper
exec-once = swaybg -i /home/danilo/Pictures/wallpaper.png

# Monitors
monitor = HDMI-A-1,highrr,0x0,1
monitor = eDP-1,highrr,1920x0,1
# monitor = eDP-1,disable

# Mirror monitors
# monitor = eDP-1,1920x1080@60,0x0,1
# monitor = ,1920x1080@60,auto,1,mirror,eDP-1

exec-once = kanshi
exec-once = dunst
exec-once = waybar
exec-once = playerctld daemon
exec-once = hyprctl setcursor Bibata-Modern-Ice 24
exec-once = /usr/lib/polkit-kde-authentication-agent-1
exec-once = ~/.config/hypr/scripts/sleep.sh
exec-once = wl-clipboard-history -t   
exec-once = wl-paste --watch cliphist store    
exec-once = rm "$HOME/.cache/cliphist/db"
exec-once = gammastep -l -9.668002:-35.737343

$wobpipe = /tmp/wobpipe
exec-once = rm -f $wobpipe && mkfifo $wobpipe && tail -f $wobpipe | wob

# Set programs that you use
$terminal = alacritty
$fileManager = thunar
$menu = kickoff

# Some default env vars.
env = XCURSOR_SIZE,24
env = QT_QPA_PLATFORMTHEME,qt5ct
env = ADW_DISABLE_PORTAL=1

general {
    gaps_in = 5
    gaps_out = 10
    border_size = 2

    col.active_border = rgba(33ccffee) rgba(00ff99ee) 45deg
    col.inactive_border = rgba(595959aa)
    resize_on_border=true
    extend_border_grab_area=20

    layout = dwindle

    allow_tearing = false
}

decoration {
    rounding = 10

    drop_shadow = yes
    shadow_range = 4
    shadow_render_power = 3
    col.shadow = rgba(1a1a1aee)

    blur {
        enabled = true
        size = 5
        passes = 1
        contrast = 1
    }
}

input {
    kb_layout = br
    kb_variant = thinkpad
    numlock_by_default = true
    repeat_delay=200

    follow_mouse = 1
    sensitivity = 0
    accel_profile = adaptive  # adaptive, flat
    scroll_method = 2fg  # edge

    touchpad {
        natural_scroll = yes
        disable_while_typing
    }
}

device:by-tech-gaming-keyboard {
    kb_layout = us,br
    kb_options = grp:win_space_toggle
}

device:by-tech-gaming-keyboard-1 {
    kb_layout = us,br
    kb_options = grp:win_space_toggle
}

animations {
    enabled = yes

    bezier = myBezier, 0.05, 0.9, 0.1, 1.05

    animation = windows, 1, 7, myBezier
    animation = windowsOut, 1, 7, default, popin 80%
    animation = border, 1, 10, default
    animation = borderangle, 1, 8, default
    animation = fade, 1, 7, default
    animation = workspaces, 1, 6, default
}

dwindle {
    pseudotile = yes # master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = yes # you probably want this
}

master {
    new_is_master = true
}

gestures {
    workspace_swipe = true
}

misc {
    disable_hyprland_logo = true
    enable_swallow = true
}

source = ./bindings.conf

windowrule = float, ^(qalculate-gtk)$
windowrule = float,^(blueman-manager)$
windowrule = float,^(pavucontrol)$
windowrule = float,^(imv)$
windowrulev2 = nomaximizerequest, class:.* # You'll probably like this.
windowrulev2 = noinitialfocus,class:^jetbrains-(?!toolbox),floating:1 # jetbrains crashing
windowrulev2 = float, class:floating

exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
