set $mod Mod4

set $left h
set $down j
set $up k
set $right l

set $term kitty
set $menu /home/danilo/git/rofi/files/launchers/type-2/launcher.sh
set $filemanager thunar
set $logout /home/danilo/git/rofi/files/powermenu/type-2/powermenu.sh

set $get_brightness light -G | awk '{ print int($1 / 1) }' 
set $set_vol wpctl set-volume -l 1.4 @DEFAULT_AUDIO_SINK@
set $get_vol wpctl get-volume @DEFAULT_AUDIO_SINK@ | awk '/^Volume:/ { if ($NF == "[MUTED]") print 0; else print int($2 * 100) }'
set $toggle_mute wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle

set $WOBSOCK $XDG_RUNTIME_DIR/wob.sock

