exec kitty & firefox & lxpolkit & playerctld daemon & dunst & gammastep & kanshi & nm-applet
exec wl-paste --watch cliphist store
exec rm -f "$HOME/.cache/cliphist/db"
exec rm -f $WOBSOCK && mkfifo $WOBSOCK && tail -f $WOBSOCK | wob

exec ~/.config/sway/scripts/empty-ws-launcher.sh
# exec libinput-gestures-setup start
