exec swaymsg "workspace 2; exec firefox;"
exec swaymsg "workspace 4; exec spotify;"
exec swaymsg "workspace 1; exec kitty;"

exec swayidle -w timeout 120 'swaylock -f -c 000000' \
            timeout 200 'swaymsg output * power off' \
            resume 'swaymsg output * power on' \
            timeout 900 'systemctl suspend' \
            before-sleep 'swaylock -f -c 000000' &
exec /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec playerctld daemon
exec swayosd-server
exec dunst
exec wl-paste -t text --watch clipman store --no-persist
exec gammastep
