exec kitty
exec chromium
exec spotify
exec /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec playerctld daemon
exec swayosd-server
exec dunst
exec rm -f "$HOME/.cache/cliphist/db"
exec wl-paste --watch cliphist store
exec gammastep
exec kanshi
exec nm-applet
