bindsym F1 exec $toggle_mute && exec $get_vol >> $WOBSOCK
bindsym F2 exec $set_vol 5%- && exec $get_vol >> $WOBSOCK
bindsym F3 exec $set_vol 5%+ && exec $get_vol >> $WOBSOCK
bindsym F5 exec light -U 5 && exec $get_brightness >> $WOBSOCK
bindsym F6 exec light -A 5 && exec $get_brightness >> $WOBSOCK

bindsym XF86AudioMute exec $toggle_mute && exec $get_vol >> $WOBSOCK
bindsym XF86AudioRaiseVolume exec $set_vol 5%+ && exec $get_vol >> $WOBSOCK
bindsym XF86AudioLowerVolume exec $set_vol 5%- && exec $get_vol >> $WOBSOCK
bindsym XF86MonBrightnessUp exec light -A 5 && exec $get_brightness >> $WOBSOCK
bindsym XF86MonBrightnessDown exec light -U 5 && exec $get_brightness >> $WOBSOCK

bindsym --locked XF86AudioPlay exec playerctl play-pause
bindsym --locked $mod+m exec playerctl play-pause
bindsym --locked XF86AudioNext exec playerctl next
bindsym --locked XF86AudioPrev exec playerctl previous

bindsym print exec slurp | grim -g - $(xdg-user-dir PICTURES)/screenshots/$(date +'screenshot_%Y-%m-%d-%H%M%S.png')
bindsym ctrl+print exec grim $(xdg-user-dir PICTURES)/screenshots/$(date +'screenshot_%Y-%m-%d-%H%M%S.png')

