output * bg ~/Pictures/wallpaper.png fill

#exec_always kill -1 $(pidof kanshi)
#output HDMI-A-1 resolution 1920x1080@75Hz position 0 0
#output eDP-1 resolution 1920x1080 position 1920 0
#output eDP-1 disable
